Modules:
  BuildFixes:
    Enable: true
    DragonEggBlocking: true  
    HalfDoors: true
    NoPhysics: true
    SpecialLogs: true
  Commands:
    Enable: true
    GetItem: true
  Environment:
    Enable: true
    DecayBlocking: true
    FormBlocking: true
    WeatherBlocking: true
NoPhysicsList:
  - 9
  - 11
  - 27
  - 28
  - 34
  - 50
  - 65
  - 66
  - 122
  - 157