name: BuildFixes
main: com.dags.BuildFixes.BuildFixes
version: 1.4

commands:
   get:
      description: Gives user stacks of 'special logs'
      usage: /get <block type> [damage]
      permission: BuildFixes.get
      permission-message: Sorry, you don't have don't have permission
   bfmodules:
      description: Enable/disable modules 
      usage: /bfmodules [buildfixes], [commands], [environment]
      permission: BuildFixes.admin
      permission-message: Sorry, you don't have don't have permission
permissions:
  BuildFixes.admin:
    description: Admin commands to enable/disable plugin features.
    default: op  
  BuildFixes.get:
    description: Allow user to use /get.
    default: op
  BuildFixes.doors:
    description: Allow user to give themselves and place wood/iron half-doors.
    default: op
  BuildFixes.eggs:
    description: Allow user to give themselves a dragon egg.
    default: op
  BuildFixes.furnace:
    description: Allow user to give themselves a burning furnace.
    default: op
  BuildFixes.logs:
    description: Allow user to give themselves a stack of each 'special log' type.
    default: op
  BuildFixes.lamps:
    description: Allow user to give themselves a stack of powered redstone lamps.
    default: op
  BuildFixes.mushrooms:
    description: Allow user to give themselves mushroom blocks.
    default: op
  BuildFixes.slabs:
    description: Allow user to give themselves double slabs.
    default: op
  BuildFixes.eggInteract:
    description: Allow user to interact with Dragon Eggs.
    default: op