name: BuildFixes
main: me.dags.BuildFixes.BuildFixes
version: 1.8.2
author: dags_

commands:
   get:
      description: Gives user 'special' blocks.
      usage: /get <item> [#damage]
      permission: BuildFixes.get
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
   fbt:
      description: Toggle fullbright on/off.
      usage: /fbt
      permission: BuildFixes.fullbright
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
   stencillist:
      description: List available Voxel stencil lists.
      usage: /stencillist
      permission: BuildFixes.stencillist
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
permissions:
  BuildFixes.builder:
    default: op
    children:
      BuildFixes.fullbright: true
      BuildFixes.get: true
      BuildFixes.doors: true
      BuildFixes.furnace: true
      BuildFixes.grass: true
      BuildFixes.logs: true
      BuildFixes.mushrooms: true
      BuildFixes.slabs: true
  BuildFixes.fullbright:
    description: Allow user to use /fb.
    default: op
  BuildFixes.stencillist:
    description: Allow user to use /stencillist.
    default: op
  BuildFixes.get:
    description: Allow user to use /get.
    default: op
  BuildFixes.doors:
    description: Allow user to give themselves and place wood/iron half-doors.
    default: op
  BuildFixes.eggs:
    description: Allow user to give themselves a dragon egg.
    default: op
  BuildFixes.furnace:
    description: Allow user to give themselves a burning furnace.
    default: op
  BuildFixes.grass:
    description: Allow user to give themselves dead-bush grasstype (placeable on grass blocks).
    default: op
  BuildFixes.logs:
    description: Allow user to give themselves a stack of each 'special log' type.
    default: op
  BuildFixes.mushrooms:
    description: Allow user to give themselves mushroom blocks.
    default: op
  BuildFixes.slabs:
    description: Allow user to give themselves double slabs.
    default: op
  BuildFixes.heads:
    description: Allow user to give themselves a player's head!
    default: op
  BuildFixes.eggInteract:
    description: Allow user to interact with Dragon Eggs.
    default: op