name: BuildFixes
main: me.dags.BuildFixes.BuildFixes
version: 1.9.3
author: dags_

commands:
   get:
      description: Gives user 'special' blocks.
      usage: /get <item> [#damage]
      permission: BuildFixes.get
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
   fbt:
      description: Toggle fullbright on/off.
      usage: /fbt
      permission: BuildFixes.fullbright
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
   vv:
      description: List content in the VoxelSniper plugin directory.
      usage: /vv <subdir> <#pagennumber>
      permission: BuildFixes.stencillist
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
   schlist:
      description: List WorlEdit schematics and subdirectories.
      usage: /schlist <subdir>
      permission: BuildFixes.schlist
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
   bf:
      description: Info command for buildfixes.
      usage: /bf [worlds], [version]
      permission: BuildFixes.bfinfo
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
   sl:
      description: StencilList generator command.
      usage: /sl [create <name>], [add <path/to/stencil>...], [save]
      permission: BuildFixes.addstencils
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
   random:
      description: Field randomiser command.
      usage: /random [radius #|range # #|probs [#] |material [names]| help]
      permission: BuildFixes.randomiser
      permission-message: Sorry, you don't have don't have permission to use that command or the argument is invalid.
permissions:
  BuildFixes.builder:
    default: op
    children:
      BuildFixes.fullbright: true
      BuildFixes.get: true
      BuildFixes.doors: true
      BuildFixes.furnace: true
      BuildFixes.grass: true
      BuildFixes.logs: true
      BuildFixes.mushrooms: true
      BuildFixes.slabs: true
      BuildFixes.randomiser: true
  BuildFixes.moderator:
    default: op
    children:
      BuildFixes.version: true
      BuildFixes.fullbright: true
      BuildFixes.get: true
      BuildFixes.doors: true
      BuildFixes.furnace: true
      BuildFixes.grass: true
      BuildFixes.logs: true
      BuildFixes.mushrooms: true
      BuildFixes.slabs: true
      BuildFixes.voxelviewer: true
      BuildFixes.addstencils: true
      BuildFixes.schlist: true
      BuildFixes.heads: true
      BuildFixes.armor: true
  BuildFixes.*:
    default: op
    children:
      BuildFixes.moderator: true
      BuildFixes.bfinfo: true
      BuildFixes.fullbright: true
      BuildFixes.get: true
      BuildFixes.eggs: true
      BuildFixes.eggInteract: true
  BuildFixes.fullbright:
    description: Allow user to use /fb.
    default: op
  BuildFixes.addstencils:
    description: Allow user to use /sl.
    default: op
  BuildFixes.voxelviewer:
    description: Allow user to use /stencillist.
    default: op
  BuildFixes.schlist:
    description: Allow user to use /schlist.
    default: op
  BuildFixes.bfinfo:
    description: Allow user to use /bf worlds.
    default: op
  BuildFixes.bfreload:
      description: Allow user to use /bf reload.
      default: op
  BuildFixes.npEdit:
        description: Allow user to use /bf np add/remove.
        default: op
  BuildFixes.get:
    description: Allow user to use /get.
    default: op
  BuildFixes.doors:
    description: Allow user to give themselves and place wood/iron half-doors.
    default: op
  BuildFixes.eggs:
    description: Allow user to give themselves a dragon egg.
    default: op
  BuildFixes.furnace:
    description: Allow user to give themselves a burning furnace.
    default: op
  BuildFixes.grass:
    description: Allow user to give themselves dead-bush grasstype (placeable on grass blocks).
    default: op
  BuildFixes.logs:
    description: Allow user to give themselves a stack of each 'special log' type.
    default: op
  BuildFixes.mushrooms:
    description: Allow user to give themselves mushroom blocks.
    default: op
  BuildFixes.slabs:
    description: Allow user to give themselves double slabs.
    default: op
  BuildFixes.heads:
    description: Allow user to give themselves a player's head!
    default: op
  BuildFixes.armor:
    description: Allow user to give themselves colored leather armor
    default: op
  BuildFixes.eggInteract:
    description: Allow user to interact with Dragon Eggs.
    default: op
  BuildFixes.randomiser:
      description: Allow user to use wheat random command
      default: true
