MultiWorldSupport:
  Enable: true
Modules:
  BuildFixes:
    Enable: true
    DragonEggBlocking: true  
    HalfDoors: true
    NoPhysics: true
    SpecialLogs: true
  Commands:
    Enable: true
    GetItem: true
    Fullbright: true
  Utilities:
    Enable: true
    SchematicsBrowser: true
    StencListBrowser: true
    StencListGenerator: true
    BuildFixesInfo: true
  Environment:
    Enable: true
    DecayBlocking: true
    FormBlocking: true
    WeatherBlocking: true
    FireSpreadBlocking: true
    AnimalBlocking: true
    MonsterBlocking: true
  MOTD:
    Enable: false
    Message: '%fA %7minecraft %8server!'
NoPhysicsList:
  - 27
  - 28
  - 34
  - 50
  - 63
  - 65
  - 66
  - 68
  - 122
  - 140
  - 157
  - 171