MultiWorldSupport:
  Enable: true
Modules:
  BuildFixes:
    Enable: true
    DragonEggBlocking: true  
    HalfDoors: true
    NoPhysics: true
    SpecialLogs: true
  Commands:
    Enable: true
    GetItem: true
    Fullbright: true
  Environment:
    Enable: true
    DecayBlocking: true
    FormBlocking: true
    MobBlocking: true
    WeatherBlocking: true
NoPhysicsList:
  - 27
  - 28
  - 34
  - 50
  - 65
  - 66
  - 122
  - 140
  - 157